version: "3"
services:
  webapi:
    image: yakimych/lift-log-web-api
    restart: always
    expose:
      - "80"
    depends_on:
      - mongodbserver

  mongodbserver:
    image: mongo
    restart: always
    volumes:
      - './mongodb:/data/db' # ./mongodb is the directory on the host machine

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - './frontend:/data/frontend'
    ports:
      - "80:80"
    links:
      - webapi
